# SPDX-License-Identifier: GPL-2.0-or-later
name: Build

env:
  KERNEL_NAME: grate
  KBUILD_DEFCONFIG: tegra_defconfig
  CROSS_COMPILE: arm-linux-gnueabihf- # build for armv7
  ARCH_SPEC_PKGS: crossbuild-essential-armhf
  ARCH: arm # build for armv7
  SCCACHE_CACHE_SIZE: 2G
  SCCACHE_DIR: /home/runner/.cache/sccache
  BUILD_PATH: /home/runner/.cache/tuxmake/builds/1

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - 'tegra_defconfig'
          - 'asus-grouper'
          - 'postmarketos-grate'
        option:
          - 'CONFIG_ARM=y' # default
          - 'CONFIG_THUMB2_KERNEL=y'
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install sccache
        env:
          LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: 0.2.15
        run: |
          export SCCACHE_FILE=sccache-v$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$LINK/v$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          chmod +x $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Enable cache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: ${{ env.SCCACHE_DIR }}
          key: ${{ env.KERNEL_NAME }}-${{ matrix.config }}-${{ matrix.option }}-${{ matrix.cc }}
      - name: Start sccache server
        run: sccache --start-server
      - name: Install dependencies
        run: |
          sudo apt-get -qq update > /dev/null
          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev bison flex libelf-dev dwarves python3-pip socat > /dev/null
          pip3 install -U --user tuxmake
      - name: Fetch postmarketos-grate config from main
        if: ${{ matrix.config == 'postmarketos-grate' }}
        run: >
          curl -L -o ${{ matrix.config }} https://gitlab.com/postmarketOS/pmaports/-/raw/master/main/linux-${{ matrix.config }}/config-${{ matrix.config }}.armv7
      - name: Fetch asus-grouper config from device/testing
        if: ${{ matrix.config == 'asus-grouper' }}
        run: >
          curl -L -o ${{ matrix.config }} https://gitlab.com/postmarketOS/pmaports/-/raw/master/device/testing/linux-${{ matrix.config }}/config-${{ matrix.config }}.armv7
      - name: Build
        run: |
          tuxmake --directory ./ -w sccache --target-arch=arm -k ${{ matrix.config }} -K ${{ matrix.option }} $TUXMAKE_EXTRA_OPTS | sed "s|^/home/runner/work/linux/linux/|::error::|"
          tar -cf linux-grate-${{ matrix.config }}-${{ matrix.cc }}.tar -C /home/runner/.cache/tuxmake/builds/1 .
          export ERRS=`grep "errors" "${BUILD_PATH}"/metadata.json | cut -d":" -f2 | tr -d " ,"`
          export WARNS=`grep "warnings" "${BUILD_PATH}"/metadata.json | cut -d":" -f2 | tr -d " ,"`
          if [ "$ERRS" != "0" ]; then
            echo "::error::Compilation failed due to $ERRS errors, please fix them."
            RET=1
          fi
          if [ "$WARNS" != "0" ]; then
            echo "::error::$WARNS warnings found, please fix them."
            RET=1
          fi
          if [ $RET = 1 ]; then
            exit 1
          fi
      - name: Stop sccache server
        run: sccache --stop-server || true
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{!startsWith(github.ref, 'refs/pull')}}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.KERNEL_NAME }}-${{ matrix.config }}-${{ matrix.option }}-${{ matrix.cc }}"
          prerelease: true
          title: "Build of Grate kernel, config ${{ matrix.config }} + ${{ matrix.option }} compiled with ${{ matrix.cc }}"
          files: |
            *.tar
  dtbs:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get -qq update > /dev/null
          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev bison flex libelf-dev dwarves python3-pip socat > /dev/null
          pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
      - name: Build
        run: |
          make $KBUILD_DEFCONFIG
          status=0
          make -j3 dtbs || status=1
          make -j3 dtbs_check || status=1
          exit $status

  dt_bindings_check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get -qq update > /dev/null
          sudo apt-get -qq install -y --no-install-recommends -o=Dpkg::Use-Pty=0 ${{ env.ARCH_SPEC_PKGS }} libyaml-dev git build-essential binutils-multiarch device-tree-compiler fakeroot libncurses5-dev libssl-dev bison flex libelf-dev dwarves python3-pip socat > /dev/null
          pip3 install -U --user git+https://github.com/devicetree-org/dt-schema.git@master
      - name: Build
        run: |
          make -j3 dt_binding_check
